name = "elixir"
entrypoint = "main.exs"
extensions = [
  "ex",
  "exs"
]
setup = [
  "wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb",
  "dpkg -i erlang-solutions_2.0_all.deb",
  "rm -r erlang-solutions_2.0_all.deb",
  "apt-get update",
  "apt-get install -y esl-erlang elixir",
]

[run]
command = [
  "elixir",
  "./main.exs"
]

[tests]

  [tests.hello]
  code = "IO.puts \"hello world\""
  output = "hello world\n"
